// CSV + print-to-PDF export helpers (no external deps).

function esc(v) {
  if (v == null) return ''
  if (Array.isArray(v)) v = v.join(' | ')
  else if (typeof v === 'object') v = JSON.stringify(v)
  v = String(v)
  return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v
}

// columns: array of strings or { key, label }
export function toCsv(rows, columns) {
  const cols = (columns || (rows[0] ? Object.keys(rows[0]) : [])).map(c => (typeof c === 'string' ? { key: c, label: c } : c))
  const header = cols.map(c => esc(c.label)).join(',')
  const body = rows.map(r => cols.map(c => esc(r[c.key])).join(',')).join('\n')
  return header + '\n' + body
}

function download(blob, filename) {
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = filename
  document.body.appendChild(a); a.click(); a.remove()
  setTimeout(() => URL.revokeObjectURL(a.href), 1000)
}

export function downloadCsv(filename, rows, columns) {
  // BOM so Excel reads UTF-8 (₹, –, etc.) correctly
  download(new Blob(['﻿' + toCsv(rows, columns)], { type: 'text/csv;charset=utf-8' }), filename)
}

export const stamp = () => new Date().toISOString().slice(0, 10)

// Open a clean printable report in a new window → user Saves as PDF.
export function printReport(title, html) {
  const w = window.open('', '_blank', 'width=900,height=1000')
  if (!w) return
  w.document.write(`<!doctype html><html><head><title>${title}</title>
    <style>
      *{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;box-sizing:border-box}
      body{margin:40px;color:#1f2937}
      h1{font-size:22px;margin:0 0 4px} .sub{color:#6b7280;font-size:13px;margin-bottom:24px}
      h2{font-size:14px;text-transform:uppercase;letter-spacing:.05em;color:#6b7280;margin:24px 0 8px;border-bottom:1px solid #e5e7eb;padding-bottom:6px}
      .grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:8px}
      .stat{border:1px solid #e5e7eb;border-radius:10px;padding:12px}
      .stat .n{font-size:24px;font-weight:800} .stat .l{font-size:12px;color:#6b7280}
      table{width:100%;border-collapse:collapse;font-size:12px} td,th{text-align:left;padding:6px 8px;border-bottom:1px solid #f0f0f0}
      th{color:#6b7280;text-transform:uppercase;font-size:10px;letter-spacing:.04em}
      .foot{margin-top:32px;color:#9ca3af;font-size:11px}
      @media print{body{margin:16px}}
    </style></head><body>${html}
    <div class="foot">Generated by PropertyInsta Admin · ${new Date().toLocaleString('en-IN')}</div>
    </body></html>`)
  w.document.close(); w.focus()
  setTimeout(() => w.print(), 350)
}
