-- ============================================================================
--  GO-LIVE — remaining admin tables (agents, reviews, quiz, meetings,
--  transactions). Run ONCE in the Supabase SQL editor (project
--  ioblbfugnhtghvxbyeos). Optional: these back the admin CMS pages; without
--  them the admin falls back to localStorage (still works, just not shared).
--
--  Already live (do NOT re-create): properties, reels, stories, investments,
--  builders, channel_partners, build_materials/services/designs/designers.
--  Run supabase/connect-content.sql separately for leads + blogs/podcasts/videos.
-- ============================================================================
SET search_path = public;

CREATE TABLE IF NOT EXISTS public.agents (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  company     text,
  phone       text,
  email       text,
  avatar      text,
  experience  text,
  rating      numeric,
  sales       integer,
  created_at  timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reviews (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user"       text,
  rating       numeric,
  "propertyId" integer,
  date         text,
  text         text,
  created_at   timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.quiz (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question   text NOT NULL,
  category   text,
  options    jsonb,
  answer     text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meetings (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      text NOT NULL,
  attendee   text,
  type       text,
  date       text,
  time       text,
  status     text,
  notes      text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.transactions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property   text,
  buyer      text,
  seller     text,
  amount     numeric,
  status     text,
  date       text,
  notes      text,
  created_at timestamptz DEFAULT now()
);

-- Permissive RLS (anon read+write), matching the other shared tables.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['agents','reviews','quiz','meetings','transactions'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS "anon_all_%1$s" ON public.%1$I;', t);
    EXECUTE format('CREATE POLICY "anon_all_%1$s" ON public.%1$I FOR ALL USING (true) WITH CHECK (true);', t);
  END LOOP;
END $$;

-- Done. The admin CMS pages for these now persist to Supabase; edits are shared.
